"""Unified structured logging engine for Iranian E-Commerce Backend.

Exports logging setup, async queue lifecycle, context bindings, security audit logger,
and pre-bound contextual loggers for all 35 backend modules.
"""

from __future__ import annotations

from app.core.logging.async_handler import (
    AsyncLogQueueManager,
    NonFormattingQueueHandler,
)
from app.core.logging.config import (
    DevConsoleRenderer,
    WordPressStyleFileFormatter,
    add_opentelemetry_context,
    bind_context,
    clear_context,
    fast_json_serializer,
    flush_logging,
    get_logger,
    redact_sensitive_data,
    setup_logging,
    shutdown_logging,
    unbind_context,
)
from app.core.logging.module_loggers import (
    MODULE_NAMES,
    analytics_logger,
    approvals_logger,
    audit_logger,
    auth_logger,
    automation_logger,
    blog_logger,
    cart_logger,
    cashback_logger,
    catalog_logger,
    checkout_logger,
    content_logger,
    core_logger,
    discounts_logger,
    gamification_logger,
    get_module_logger,
    integrations_logger,
    inventory_logger,
    loyalty_logger,
    media_logger,
    messaging_logger,
    notifications_logger,
    orders_logger,
    payments_logger,
    rbac_logger,
    recommendations_logger,
    referrals_logger,
    reviews_logger,
    search_logger,
    seo_logger,
    settings_logger,
    shared_logger,
    shipping_logger,
    support_logger,
    users_logger,
    vendors_logger,
    wallet_logger,
    wishlist_logger,
    worker_logger,
)
from app.core.logging.security_audit import log_security_event

__all__ = [
    "MODULE_NAMES",
    "AsyncLogQueueManager",
    "DevConsoleRenderer",
    "NonFormattingQueueHandler",
    "WordPressStyleFileFormatter",
    "add_opentelemetry_context",
    "analytics_logger",
    "approvals_logger",
    "audit_logger",
    "auth_logger",
    "automation_logger",
    "bind_context",
    "blog_logger",
    "cart_logger",
    "cashback_logger",
    "catalog_logger",
    "checkout_logger",
    "clear_context",
    "content_logger",
    "core_logger",
    "discounts_logger",
    "fast_json_serializer",
    "flush_logging",
    "gamification_logger",
    "get_logger",
    "get_module_logger",
    "integrations_logger",
    "inventory_logger",
    "log_security_event",
    "loyalty_logger",
    "media_logger",
    "messaging_logger",
    "notifications_logger",
    "orders_logger",
    "payments_logger",
    "rbac_logger",
    "recommendations_logger",
    "redact_sensitive_data",
    "referrals_logger",
    "reviews_logger",
    "search_logger",
    "seo_logger",
    "settings_logger",
    "setup_logging",
    "shared_logger",
    "shipping_logger",
    "shutdown_logging",
    "support_logger",
    "unbind_context",
    "users_logger",
    "vendors_logger",
    "wallet_logger",
    "wishlist_logger",
    "worker_logger",
]
