"""add_tax_and_outbox

Revision ID: 01bc8bed842e
Revises: ec9dd94538b4
Create Date: 2026-09-10 20:30:12.822211+03:30

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "01bc8bed842e"
down_revision: Union[str, None] = "ec9dd94538b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.String(length=100), nullable=False),
        sa.Column("correlation_id", sa.String(length=100), nullable=True),
        sa.Column("causation_id", sa.String(length=100), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CLAIMED",
                "PROCESSING",
                "PROCESSED",
                "FAILED",
                "DEAD_LETTER",
                name="outbox_status_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("worker_id", sa.String(length=100), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_messages")),
    )
    op.create_index(
        "ix_outbox_aggregate", "outbox_messages", ["aggregate_type", "aggregate_id"], unique=False
    )
    op.create_index("ix_outbox_created_at", "outbox_messages", ["created_at"], unique=False)
    op.create_index("ix_outbox_event_type", "outbox_messages", ["event_type"], unique=False)
    op.create_index(
        "ix_outbox_status_available", "outbox_messages", ["status", "available_at"], unique=False
    )
    op.create_table(
        "tax_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "STANDARD",
                "REDUCED",
                "EXEMPT",
                "ZERO",
                name="tax_category_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("jurisdiction", sa.String(length=50), nullable=False),
        sa.Column("rate_basis_points", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_compound", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_rules")),
        sa.UniqueConstraint("code", name=op.f("uq_tax_rules_code")),
    )
    op.create_index("ix_tax_rules_category", "tax_rules", ["category"], unique=False)
    op.create_index("ix_tax_rules_code", "tax_rules", ["code"], unique=True)
    op.create_index(
        "ix_tax_rules_effective_dates",
        "tax_rules",
        ["effective_from", "effective_to"],
        unique=False,
    )
    op.create_index("ix_tax_rules_is_active", "tax_rules", ["is_active"], unique=False)
    op.create_index("ix_tax_rules_jurisdiction", "tax_rules", ["jurisdiction"], unique=False)
    op.alter_column("media_assets", "uploader_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("media_assets", "uploader_id", existing_type=sa.UUID(), nullable=False)
    op.drop_index("ix_tax_rules_jurisdiction", table_name="tax_rules")
    op.drop_index("ix_tax_rules_is_active", table_name="tax_rules")
    op.drop_index("ix_tax_rules_effective_dates", table_name="tax_rules")
    op.drop_index("ix_tax_rules_code", table_name="tax_rules")
    op.drop_index("ix_tax_rules_category", table_name="tax_rules")
    op.drop_table("tax_rules")
    op.drop_index("ix_outbox_status_available", table_name="outbox_messages")
    op.drop_index("ix_outbox_event_type", table_name="outbox_messages")
    op.drop_index("ix_outbox_created_at", table_name="outbox_messages")
    op.drop_index("ix_outbox_aggregate", table_name="outbox_messages")
    op.drop_table("outbox_messages")
    # ### end Alembic commands ###
