"""add_payment_webhook_events

Revision ID: 41444c67e586
Revises: 01bc8bed842e
Create Date: 2026-09-11 00:14:51.551428+03:30

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "41444c67e586"
down_revision: Union[str, None] = "01bc8bed842e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_webhook_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("payment_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            name=op.f("fk_payment_webhook_events_payment_id_payments"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_webhook_events")),
        sa.UniqueConstraint("provider", "event_id", name="uq_webhook_provider_event_id"),
    )
    op.create_index(
        "ix_webhook_events_created_at", "payment_webhook_events", ["created_at"], unique=False
    )
    op.create_index(
        "ix_webhook_events_event_id", "payment_webhook_events", ["event_id"], unique=False
    )
    op.create_index(
        "ix_webhook_events_provider", "payment_webhook_events", ["provider"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_webhook_events_provider", table_name="payment_webhook_events")
    op.drop_index("ix_webhook_events_event_id", table_name="payment_webhook_events")
    op.drop_index("ix_webhook_events_created_at", table_name="payment_webhook_events")
    op.drop_table("payment_webhook_events")
    # ### end Alembic commands ###
