"""add_messaging_and_vendors

Revision ID: ec9dd94538b4
Revises: b48724723233
Create Date: 2026-09-10 02:07:54.238113+03:30

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ec9dd94538b4"
down_revision: Union[str, None] = "b48724723233"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "broadcast_campaigns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "SMS", "EMAIL", "PUSH", "IN_APP", name="campaign_channel_enum", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "target_segment",
            sa.Enum(
                "ALL_USERS",
                "ACTIVE_BUYERS",
                "INACTIVE_USERS",
                "ABANDONED_CARTS",
                "WISHLIST_USERS",
                name="target_segment_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("message_template", sa.Text(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SCHEDULED",
                "PROCESSING",
                "SENT",
                "FAILED",
                "CANCELLED",
                name="campaign_status_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("total_recipients", sa.Integer(), server_default="0", nullable=False),
        sa.Column("success_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("fail_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("ab_test_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("variant_b_template", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broadcast_campaigns")),
    )
    op.create_index(
        "ix_broadcast_campaigns_channel", "broadcast_campaigns", ["channel"], unique=False
    )
    op.create_index(
        "ix_broadcast_campaigns_created_at", "broadcast_campaigns", ["created_at"], unique=False
    )
    op.create_index(
        "ix_broadcast_campaigns_scheduled_at",
        "broadcast_campaigns",
        ["scheduled_at"],
        unique=False,
    )
    op.create_index(
        "ix_broadcast_campaigns_status", "broadcast_campaigns", ["status"], unique=False
    )
    op.create_index(
        "ix_broadcast_campaigns_target_segment",
        "broadcast_campaigns",
        ["target_segment"],
        unique=False,
    )
    op.create_table(
        "broadcast_recipients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SENT", "FAILED", name="recipient_status_enum", native_enum=False),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("variant_used", sa.String(length=10), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["broadcast_campaigns.id"],
            name=op.f("fk_broadcast_recipients_campaign_id_broadcast_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_broadcast_recipients_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broadcast_recipients")),
        sa.UniqueConstraint(
            "campaign_id", "user_id", name="uq_broadcast_recipients_campaign_user"
        ),
    )
    op.create_index(
        "ix_broadcast_recipients_campaign_id",
        "broadcast_recipients",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        "ix_broadcast_recipients_status", "broadcast_recipients", ["status"], unique=False
    )
    op.create_index(
        "ix_broadcast_recipients_user_id", "broadcast_recipients", ["user_id"], unique=False
    )
    op.create_table(
        "vendors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("store_name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=250), nullable=False),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("banner_url", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("commission_rate", sa.Integer(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("national_id", sa.String(length=20), nullable=True),
        sa.Column("iban_number", sa.String(length=50), nullable=True),
        sa.Column("contact_phone", sa.String(length=30), nullable=True),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("total_sales_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_vendors_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendors")),
        sa.UniqueConstraint("slug", name=op.f("uq_vendors_slug")),
        sa.UniqueConstraint("user_id", name=op.f("uq_vendors_user_id")),
    )
    op.create_index("ix_vendors_is_active", "vendors", ["is_active"], unique=False)
    op.create_index("ix_vendors_is_verified", "vendors", ["is_verified"], unique=False)
    op.create_index("ix_vendors_slug", "vendors", ["slug"], unique=False)
    op.create_index("ix_vendors_user_id", "vendors", ["user_id"], unique=False)
    op.create_table(
        "vendor_settlements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "PAID",
                "REJECTED",
                name="settlement_status_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("payment_reference", sa.String(length=100), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_vendor_settlements_vendor_id_vendors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_settlements")),
    )
    op.create_index(
        "ix_vendor_settlements_created_at", "vendor_settlements", ["created_at"], unique=False
    )
    op.create_index("ix_vendor_settlements_status", "vendor_settlements", ["status"], unique=False)
    op.create_index(
        "ix_vendor_settlements_vendor_id", "vendor_settlements", ["vendor_id"], unique=False
    )
    op.add_column("product_variants", sa.Column("vendor_id", sa.UUID(), nullable=True))
    op.create_index(
        "ix_product_variants_vendor_id", "product_variants", ["vendor_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_product_variants_vendor_id_vendors"),
        "product_variants",
        "vendors",
        ["vendor_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("products", sa.Column("vendor_id", sa.UUID(), nullable=True))
    op.create_index("ix_products_vendor_id", "products", ["vendor_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_products_vendor_id_vendors"),
        "products",
        "vendors",
        ["vendor_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_products_vendor_id_vendors"), "products", type_="foreignkey")
    op.drop_index("ix_products_vendor_id", table_name="products")
    op.drop_column("products", "vendor_id")
    op.drop_constraint(
        op.f("fk_product_variants_vendor_id_vendors"), "product_variants", type_="foreignkey"
    )
    op.drop_index("ix_product_variants_vendor_id", table_name="product_variants")
    op.drop_column("product_variants", "vendor_id")
    op.drop_index("ix_vendor_settlements_vendor_id", table_name="vendor_settlements")
    op.drop_index("ix_vendor_settlements_status", table_name="vendor_settlements")
    op.drop_index("ix_vendor_settlements_created_at", table_name="vendor_settlements")
    op.drop_table("vendor_settlements")
    op.drop_index("ix_vendors_user_id", table_name="vendors")
    op.drop_index("ix_vendors_slug", table_name="vendors")
    op.drop_index("ix_vendors_is_verified", table_name="vendors")
    op.drop_index("ix_vendors_is_active", table_name="vendors")
    op.drop_table("vendors")
    op.drop_index("ix_broadcast_recipients_user_id", table_name="broadcast_recipients")
    op.drop_index("ix_broadcast_recipients_status", table_name="broadcast_recipients")
    op.drop_index("ix_broadcast_recipients_campaign_id", table_name="broadcast_recipients")
    op.drop_table("broadcast_recipients")
    op.drop_index("ix_broadcast_campaigns_target_segment", table_name="broadcast_campaigns")
    op.drop_index("ix_broadcast_campaigns_status", table_name="broadcast_campaigns")
    op.drop_index("ix_broadcast_campaigns_scheduled_at", table_name="broadcast_campaigns")
    op.drop_index("ix_broadcast_campaigns_created_at", table_name="broadcast_campaigns")
    op.drop_index("ix_broadcast_campaigns_channel", table_name="broadcast_campaigns")
    op.drop_table("broadcast_campaigns")
    # ### end Alembic commands ###
